### ISSUE TITLE
Alternative Idea? ATX Extension Cable Mod

### ISSUE THREAD

**Issue by bradmkjr** [necroware/voltage-blaster#1]
Instead of taking up a valuable ISA slot on the motherboard, why can't an ATX extension cable be used to inject -5V between the power supply and the motherboard?

https://www.amazon.com/Power-Supply-Motherboard-Extension-Inches/dp/B01MQRBQBI
https://www.amazon.com/Cable-Matters-Motherboard-Power-Extension/dp/B01DV1Z66C

Could the same components be soldered inline on the extension cable or on a smaller board?

Feel free to close this issue, just wanted to share my idea and see what others thought.

Thanks,
Brad

**Comment by D4no0** [comment]
This can be done no problem, the question is: will you pay 5x the price of that board to get the extension cables? those connectors tend to be quite expensive.

**Comment by necroware** [comment]
I think this is also a good proposal, but it would be a completely different solution for the same problem. So, I think, if we do this, we would create another project. This project is about doing it as an ISA card with all the pros and contras.
